# Generated by Django 2.0.1 on 2022-04-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='value',
            field=models.CharField(default=0, max_length=32, verbose_name='数值'),
        ),
    ]
