# Generated by Django 2.0.1 on 2022-04-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20220413_1746'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Model_POSCAR',
        ),
        migrations.RemoveField(
            model_name='model_incar',
            name='title',
        ),
        migrations.AddField(
            model_name='model_incar',
            name='parameter',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='参数'),
        ),
    ]
