# Generated by Django 2.0.1 on 2022-04-21 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20220413_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSCAR_Down',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文件名称')),
                ('file', models.FileField(upload_to='POSCAR_download/', verbose_name='文件路径')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2022, 4, 21, 15, 57, 35, 610590), verbose_name='文件添加时间')),
            ],
        ),
    ]
